[project]
name = "agentic-cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10"
dependencies = [
    "agno>=1.2.16",
    "dotenv>=0.9.9",
    "duckduckgo-search>=8.0.0",
    "lancedb>=0.21.2",
    "numexpr>=2.10.2",
    "pandas>=2.2.3",
    "pylance>=0.25.2",
    "pypdf>=5.4.0",
    "tantivy>=0.22.2",
    "yfinance>=0.2.55",
]
