[project]
name = "agent-cookbook"
version = "0.1.0"
description = ""
authors = [
    { name = "He Fei", email = "droxer.he@gmail.com" }
]
requires-python = ">=3.11,<3.13"
dependencies = [
    "crewai[tools]==0.76.9",
    "langfuse==2.50.2",
    "pydotenv==0.0.7",
    "flaml[automl]==2.3.2",
    "lightrag-hku==1.0.6",
    "aioboto3==13.2.0",
    "torch==2.5.1",
    "transformers==4.47.1",
    "nano-vectordb==0.0.4.3",
    "ollama>=0.4.7",
    "deepsearcher>=0.0.1rc2",
    "icecream>=2.1.4",
] 
