[project]
name = "agent-cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10"
dependencies = [
    "crewai>=0.102.0",
    "dotenv>=0.9.9",
    "langchain-community>=0.3.10",
    "langchain-postgres>=0.0.14",
    "langgraph>=0.3.28",
]
